FROM python:3.8

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api .

ENV POSTGRES_USER=$INPUT_POSTGRES_USER
ENV POSTGRES_PASSWORD=$INPUT_POSTGRES_PASSWORD
ENV POSTGRES_DB=$INPUT_POSTGRES_DB
ENV POSTGRES_HOST=$INPUT_POSTGRES_HOST
ENV POSTGRES_PORT=$INPUT_POSTGRES_PORT

CMD [ "python", "./main.py"]