FROM python:3.8

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api .

ARG user
ENV POSTGRES_USER=$user
ARG pwd
ENV POSTGRES_PASSWORD=$pwd
ARG db
ENV POSTGRES_DB=$db
ARG host
ENV POSTGRES_HOST=$host
ARG port
ENV POSTGRES_PORT=$port

CMD [ "python", "./main.py"]