default_context:
  project_name: 'fin_app_api'
  project_slug: 'api'
  domain_main: 'vast-sea-49086.herokuapp.com'
  domain_staging: 'vast-sea-49086.herokuapp.com'
  docker_swarm_stack_name_main: 'vast-sea-49086.herokuapp.com'
  docker_swarm_stack_name_staging: 'vast-sea-49086.herokuapp.com'
  secret_key: 'felix'
  first_superuser: 'felix'
  first_superuser_password: 'felix'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.vast-sea-49086.herokuapp.com", "https://vast-sea-49086.herokuapp.com", "https://vast-sea-49086.herokuapp.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@vast-sea-49086.herokuapp.com'
  postgres_password: 'test'
  pgadmin_default_user: 'test'
  pgadmin_default_user_password: 'test'
  traefik_constraint_tag: 'test'
  traefik_constraint_tag_staging: 'test'
  traefik_public_constraint_tag: 'test'
  flower_auth: 'test'
  sentry_dsn: 'test'
  docker_image_prefix: 'test'
  docker_image_backend: 'test'
  docker_image_celeryworker: 'test'
  docker_image_frontend: 'test'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
