name: Build Docker images and deploy to Heroku
on:
  push:
    branches:
    - develop

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build, push and deploy backend to heroku
        env:
          CONTAINER_SECRET: ${{ secrets.CONTAINER_SECRET }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          CONTAINER_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        run: |
          doBuild()
          {
            name=$1
            dockerfile=$2
            app_name=$3
            proc_type=$4
            echo "building $name"
            pwd
            ls
            containerName="${name}"
            docker build . --file $dockerfile --tag $CONTAINER_REGISTRY/$containerName
            docker tag $CONTAINER_REGISTRY/$containerName $CONTAINER_REGISTRY/$app_name/$proc_type
            docker push $CONTAINER_REGISTRY/$app_name/$proc_type
          }

          doBuild "ui" "Dockerfile.front" "gentle-caverns-79193" "web";